### ISSUE TITLE
Error when validate using getMCLC

### ISSUE THREAD

**Issue by GamesX50** [Hanro50/MSMC#14]
There is a error if you use msauth.getMCLC().validate(variable);

(node:15352) UnhandledPromiseRejectionWarning: ReferenceError: FETCH is not defined
    at Object.validate (node_modules\msmc\modules\mclc.js:42:19)
    at IpcMainImpl.<anonymous> (index.js:42:30)       
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:9469)
    at Object.emit (events.js:315:20)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:15352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:15352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I am searching in the main code and I found the solution. In the function validate of the class mclc.js put this in the first line of the function:
const FETCH = BE.getFetch(); 

When I put it, the error doesn't display anymore.

**Comment by Hanro50** [comment]
Thank you for the bug report. I'll push a patch out as fast as possible.

**Comment by GamesX50** [comment]
You're welcome :)

And another thing, the client_token is always null.

**Comment by GamesX50** [comment]
You're welcome 😄

**Comment by Hanro50** [comment]
No problem. Also, the Client_token is set by MCLC's internal code...MSMC just forwards it in a sense.
