### ISSUE TITLE
Error in the function validate in class mclc.js

### ISSUE THREAD

**Issue by GamesX50** [Hanro50/MSMC#15]
Hi, I'm creating my own launcher and I'm creating a login system using your library. When I trying to validate if the token is valid, using the getMCLC().validate(), I doesn't work. I checked the function validate of the code mclc.js, and I found a error in this part of the code:
        const FETCH = BE.getFetch();
        if (profile._msmc) {
            return msmc.validate(his.toProfile(profile)); -> This part 
        }
In the part that I marked, I changed his.profile to this.profile and it's work great.
Thanks, I wait to your response.

**Comment by Hanro50** [comment]
I'll check it out. The msmc module did get refactored a while back and mistakes like that have unfortunately slipped through.

**Comment by GamesX50** [comment]
Don't worry, is normal why creating a library with a lot of code

**Comment by Hanro50** [comment]
I'll be pushing a fix asap

**Comment by Hanro50** [comment]
If you're on the project's discord server. Just give me your username and tag and I'll give you the role for the bug finder role. Other than that the bug should be fixed and pushed to npm

**Comment by GamesX50** [comment]
I entered the Discord. My username is GamesX50#1762

**Comment by Hanro50** [comment]
👍You should now have the role

**Comment by GamesX50** [comment]
Thanks :D
