### ISSUE TITLE
An Error With Gamertag Ans GameDisplayName "?."

### ISSUE THREAD

**Issue by Nokaji** [Hanro50/MSMC#31]
We can't in /app/assets/js/settings/user-account.js call the line "const { Auth } = require("msmc").
Error in the console -> (App threw an error during load - Error: Cannot find module 'msmc'). So i have put the direct link, like that "const { Auth } = require("../node_modules/msmc/dist/index.js");", then i have a other problem : https://pastebin.com/X5BHfWia
So I went to find all the "?." in msmc, and finally it's good. More detail here : https://discord.gg/FqZk2bmWZG -> Support -> "Problem With Msmc and may be my brain x)"

**Comment by Matix-Media** [comment]
Seems like you are using an outdated version of typescript

**Comment by Nokaji** [comment]
I don't using typescript

**Comment by Matix-Media** [comment]
Which node version are you using?

**Comment by Nokaji** [comment]
> Which node version are you using?

The latest (18.x.x)

**Comment by Hanro50** [comment]
This is currently an issue in 4.x builds of msmc. This should be resolved in version 5.x

**Comment by Matix-Media** [comment]
@Nokaji have you tried updating to `5.*`?

**Comment by Nokaji** [comment]
No not yet, I saw the update and I plan to try in a few days if I don't forget

**Comment by Matix-Media** [comment]
Okay, I will mark this issue as resolved. Since it should be patched in 5.*
