### ISSUE TITLE
Error with "import { Auth } from 'msmc'"

### ISSUE THREAD

**Issue by Koriita0** [Hanro50/MSMC#32]
I have a project where I'm using electron+react to launch minecraft. But when trying to import msmc to authenticate I get this error

internal/modules/cjs/loader.js:683 Uncaught (in promise) Error: Cannot find module 'msmc'
Require stack:

So, i cant use that. Try to import it in many ways, for example:

const { Auth } = require('msmc')

import Auth from 'msmc';

I even tried using IPC, but in all of them I got the same error. I'm using the latest version of msmc 

Thank's

**Comment by Hanro50** [comment]
This is fixed in version 5.0.0
