### ISSUE TITLE
how to use nw.js instead of raw

### ISSUE THREAD

**Issue by Rylazius** [Hanro50/MSMC#40]
cuz i use firefox and raw doesnt work plus electron requires backend

**Comment by Hanro50** [comment]
https://nwjs.io/

The nwjs framework is a reference to the above project. 

Raw is meant for when you're using no framework or library akin to nwjs or electron. It instead searches your computer for a supported chromium based browser (or Firefox on Linux) and uses that instead. 

Most modern versions of Windows 10 and all version of 11 ship with one such browser, namely Microsoft Edge.

**Comment by Rylazius** [comment]
k but how to use it? like any examples?

**Comment by Hanro50** [comment]
You follow the example of how to setup a nwjs project and them you import msmc into that. You can then use then use  "nwjs" instead of "raw" or "electron".
