### ISSUE TITLE
Make MSMC not show console messages

### ISSUE THREAD

**Issue by DeveloLongScript** [Hanro50/MSMC#42]
Simple. When authenticating, add a switch to make it so console messages don't send while authenticating.

**Comment by Hanro50** [comment]
That's easier said then done and it has the potential to interfere with some debug tools

**Comment by giftedl** [comment]
Alright thanks, its just when people read Electron stuff, I don't think they want to see a lot of jumble when authenticating. Respect your stuff, you really help me.
